brand: hushicai
permalink: /:year/:month/:day/:title.html
pygments: true
exclude: [ "README.md", "Rakefile", "changelog.md"]
markdown: redcarpet

author:
    name: hushicai
    email: bluthcy@gmail.com
