permalink: /:categories/:year/:month/:day/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

title : hushicai               
brand: Wuning
author :
  name : hushicai
  email : bluthcy@gmail.com


team:
  - name: hushicai
    email: bluthcy@gmail.com
    hash: 247a526e104f4c65067a7d7a527bf034
  - name: hushc
    email: 778496804@qq.com
    hash: 7f88bc053734d177d746401d0685200a
