permalink: /:categories/:year/:month/:day/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

title : hushicai               
brand: Wuning
author :
  name : hushicai
  email : bluthcy@gmail.com
