destination: /Users/hushicai/temp/blog
brand: hushicai
permalink: /:year/:month/:day/:title.html
pygments: true
exclude: [ "README.md", "Rakefile", "changelog.md"]
markdown: redcarpet

paginate: 5 

author:
    name: hushicai
    email: bluthcy@gmail.com
